# Generated by Django 5.1.4 on 2025-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geez_app', '0002_rename_antonyms_gis_ለሴ_rename_phonetic_gis_መድ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gis',
            name='ባዕ_ጥ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ባዕ ጥ'),
        ),
        migrations.AlterField(
            model_name='gis',
            name='ተጨማሪ_ማብራሪያ',
            field=models.TextField(blank=True, null=True, verbose_name='ተጨማሪ ማብራሪያ'),
        ),
        migrations.AlterField(
            model_name='gis',
            name='የሰ_ስ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='የሰ.ስ'),
        ),
    ]
