# Generated by Django 5.1.4 on 2025-01-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geez_app', '0003_alter_gis_ባዕ_ጥ_alter_gis_ተጨማሪ_ማብራሪያ_alter_gis_የሰ_ስ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gis',
            name='ለአንድ_ለብ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ለአንድ ለብዙ'),
        ),
    ]
